In [9]:
import pandas as pd
import numpy as np

In [10]:
# waitlist and enrollment data
wl=pd.read_csv("onlywaitlists.csv")
wl

Class        Data  BCCR1  BCCR2  BCCR3  BCCR4  CCCOMA3  CCCOMA4  \
0      TOTALS         NaN    132    131    106     89        9       10   
1   CBMFW4761  enrollment      1      1      1      2        0        0   
2   CBMFW4761    waitlist      0      0      0      0        0        0   
3   COMSE6111  enrollment      0      0      0      0        0        0   
4   COMSE6111    waitlist      0      0      0      3        0        0   
..        ...         ...    ...    ...    ...    ...      ...      ...   
82  CSEEW4840    waitlist      0      0      0      0        0        0   
83  CSORW4231  enrollment      0      0      0      0        0        0   
84  CSORW4231    waitlist      0      0      7      3        2        0   
85  ENGIE1006  enrollment      7      9      1      2        0        0   
86  ENGIE1006    waitlist      0      0      0      0        0        0   

    CCCOMS3  CCCOMS4  ...  GOSTAT2  GSCSCA3  GSCSCA4  GSFNEC4  GSUNDC2  \
0       103      108  ...        0       62      109        5       35   
1         3        0  ...        0        0        4        0        0   
2         0        0  ...        0        0        0        0        0   
3         0        0  ...        0        0        0        0        0   
4         5       12  ...        0        2        5        0        0   
..      ...      ...  ...      ...      ...      ...      ...      ...   
82        0        1  ...        0        1        1        0        0   
83        0        0  ...        0        0        0        0        0   
84        5        4  ...        0        6        7        0        0   
85        0        1  ...        0        0        0        1        3   
86        0        0  ...        0        0        0        0        0   

    GSUNDC3  PHBION1  OTHER  Total    Cap  
0        42        0    NaN    NaN    NaN  
1         0        0   14.0   48.0   50.0  
2         0        0    0.0    0.0    NaN  
3         0        0    0.0    1.0   75.0  
4         0        0    5.0  172.0    NaN  
..      ...      ...    ...    ...    ...  
82        0        0    0.0   46.0    NaN  
83        0        0    0.0    0.0  200.0  
84        0        0   23.0  193.0    NaN  
85        2        0   22.0  184.0  200.0  
86        0        0    0.0    0.0    NaN  

[87 rows x 47 columns]

In [11]:
# data on what each of the group names mean
st=pd.read_csv( "students.csv")
st

Program                                       Program_Name  Degree  \
0   CCCOMA                   COMPUTER SCIENCE AND MATHEMATICS  AB       
1   CCCOMS                                   COMPUTER SCIENCE  AB       
2   CCCOST                    COMPUTER SCIENCE AND STATISTICS  AB       
3   CCDTSC  DATA SCIENCE                                  ...  AB       
4   CCINFS                               INFORMATION SCIENCES  AB       
5   CMCOMS                                   COMPUTER SCIENCE  AB       
6   CNCOMS                                   COMPUTER SCIENCE  AB       
7   CS/MBA         DUAL MS/MBA: COMPUTER SCIENCE AND BUSINESS  MS       
8   EACSIS                                Information Systems  CPF      
9   EACSIT                                Intelligent Systems  CPF      
10  EACSNS                             Networking and Systems  CPF      
11  EDCOMS                                   COMPUTER SCIENCE  DES      
12  EKCBIO                              COMPUTATIONAL BIOLOGY  NDG      
13  EKCSEC                                  COMPUTER SECURITY  NDG      
14  EKFDCS                    FOUNDATIONS OF COMPUTER SCIENCE  NDG      
15  EKMLRN                                   MACHINE LEARNING  NDG      
16  EKNLPR                        NATURAL LANGUAGE PROCESSING  NDG      
17  EKNSYS                                    NETWORK SYSTEMS  NDG      
18  EKPERS                                       PERSONALIZED  NDG      
19  EKSSYS                                   SOFTWARE SYSTEMS  NDG      
20  EKTHES                                             THESIS  NDG      
21  EKVSGR                                  VISION & GRAPHICS  NDG      
22  EMCOMS                                   COMPUTER SCIENCE  MS       
23  EMCSAP                     COMPUTER SCIENCE ALIGN PROGRAM  NDG      
24  EMCSJN           DUAL MS -- COMPUTER SCIENCE & JOURNALISM  MS       
25  EMIDSE  DATA SCIENCE                                  ...  MS       
26  EMIDSO  DATA SCIENCE ONLINE                           ...  MS       
27  ENCMEN                               COMPUTER ENGINEERING  BS       
28  ENCOMS                                   COMPUTER SCIENCE  BS       
29  EPCSE                        COMPUTER SYSTEMS ENGINEERING  CSE      
30  ESCOMS                                   COMPUTER SCIENCE  NDG      
31  ETCOMS                   MS/PHD TRACK -- COMPUTER SCIENCE  MS       
32  EUCSE                        COMPUTER SYSTEMS ENGINEERING  CSE      
33  EVCOMS                                   COMPUTER SCIENCE  MS       
34  EWCOMS                   MS/PHD TRACK -- COMPUTER SCIENCE  MS       
35  EYCOMS                                   COMPUTER SCIENCE  DES      
36  GCCOMS                                   COMPUTER SCIENCE  BS       
37  GCCSCA                                   COMPUTER SCIENCE  BA       
38  GDCOMS                                   COMPUTER SCIENCE  PHD      
39  GICOMS                                   COMPUTER SCIENCE  BS       
40  GLCOMS                                   COMPUTER SCIENCE  PHM      
41  GSCOMA                   COMPUTER SCIENCE AND MATHEMATICS  BA       
42  GSCOMS                                   COMPUTER SCIENCE  BS       
43  GSCOST                    COMPUTER SCIENCE AND STATISTICS  BA       
44  GSCSCA                                   COMPUTER SCIENCE  BA       
45  GSDTSC  DATA SCIENCE                                  ...  BA       
46  GSINFA                               INFORMATION SCIENCES  BA       
47  GSINFS                               INFORMATION SCIENCES  BS       
48  VMCOMS                                   COMPUTER SCIENCE  MS       

       Cert_Type School Department Bill_Program_Flag Interdisciplinary_Flag  \
0   MAJOR          CC         COMS                 Y                      N   
1   MAJOR          CC         COMS                 Y                      N   
2   MAJOR          CC         COMS                 Y                      N   
3   MAJOR          CC         COMS  

In [19]:
# sum together enrollment and waitlist data
wl_data=wl.groupby(['Class']).sum().reset_index()
# dtop the row the totals waitlist number per class
wl_data=wl_data.drop(43)
# drop excess column/rows, transpose to get groups as rows
wl_tr=wl_data.drop(['Class'], axis=1).transpose()
wl_tr=wl_tr.drop(["OTHER", "Total", "Cap"], axis=0)
# compute the total number of waitlists per group
wl_tr["total waitlists"]=wl_tr.sum(axis=1)
# total number of students in each group
wl_tr["total students"]=wl.iloc[0]

# compute the ratio betweem waitlists and total students
# this ratio can be interpeted as the average number of waitlists joined by students in this group
wl_tr["ratio"]=wl_tr["total waitlists"]/wl_tr["total students"]
# divide the number of waitlists per each course by the total number of waitlists
# this can be interpreted as the probability that a student in this group would join the waitlist for this particular class
wl_final=wl_tr[range(0,43)].div(wl_tr["total waitlists"], axis=0)
# bring back the previous columns, fill in naN values with 0
wl_final['waitlist']=wl_tr["total waitlists"]
wl_final['students']=wl_tr["total students"]
wl_final['ratio']=wl_tr["ratio"]
wl_final=wl_final.fillna(0)
wl_final

        Class                Data  BCCR1  BCCR2  BCCR3  BCCR4  CCCOMA3  \
0   CBMFW4761  enrollmentwaitlist      1      1      1      2        0   
1   COMSE6111  enrollmentwaitlist      0      0      0      3        0   
2   COMSE6156  enrollmentwaitlist      0      0      1      2        0   
3   COMSE6178  enrollmentwaitlist      0      1      7      4        0   
4   COMSE6261  enrollmentwaitlist      0      0      0      0        0   
5   COMSE6424  enrollmentwaitlist      0      0      0      1        0   
6   COMSE6732  enrollmentwaitlist      0      0      0      0        0   
7   COMSE6915  enrollmentwaitlist      0      0      0      0        0   
8   COMSE6998  enrollmentwaitlist      0      0      0      3        0   
9   COMSW1004  enrollmentwaitlist     63     14     13      4        0   
10  COMSW1404  enrollmentwaitlist      3      0      0      0        0   
11  COMSW3102  enrollmentwaitlist      0      0      4      0        0   
12  COMSW3132  enrollmentwaitlist     

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [ ]:
# samples a normal distribution
# need to figure out standard deviation--> could ask for this data? or just use a random number like 1
# sets any negative values to 0
def sample_class_num(mean, std, N):
  sample=np.round(np.random.normal(mean, std, N))
  sample[sample<0]=0
  return sample

# randomly chooses courses according to the distribution
def course_ranking(class_num, course_prob):
  return np.random.choice(44,class_num,p=course_prob, replace=False)

# for a certain group compute a sample of course rankings
def sample_course_ranking(group):
  cr=wl_final.loc[group]
  class_num=sample_class_num(cr.ratio, 1, int(cr.students)).astype(int)
  vec=cr[range(0,43)]
  vec=np.array(np.append(vec,1-vec.sum()))
  rank=[course_ranking(x, vec) for x in class_num]
  return rank


In [ ]:
sample_class_num(4,1,10)

array([4., 4., 4., 4., 4., 3., 4., 3., 3., 3.])

In [ ]:
#SLIGHT BUG HERE, probabilities don't sum to 1
rank=sample_course_ranking("GSUNDC3")
rank

[array([9]),
 array([13, 28]),
 array([37]),
 array([13,  9]),
 array([37]),
 array([13, 33]),
 array([28]),
 array([13, 16, 19]),
 array([16, 13]),
 array([14, 15]),
 array([13, 16]),
 array([13, 15]),
 array([13]),
 array([15, 13, 37]),
 array([13, 35, 22, 15]),
 array([14, 28,  9]),
 array([13, 35]),
 array([15, 13]),
 array([], dtype=int64),
 array([9]),
 array([], dtype=int64),
 array([15]),
 array([15, 17]),
 array([], dtype=int64),
 array([35,  9]),
 array([14, 15, 13]),
 array([42, 13, 28]),
 array([], dtype=int64),
 array([9]),
 array([37, 15, 42]),
 array([ 9, 13]),
 array([ 9, 14, 13]),
 array([12]),
 array([22, 35]),
 array([28]),
 array([ 9, 12]),
 array([13]),
 array([14]),
 array([35, 14]),
 array([35, 15]),
 array([13, 14, 37]),
 array([28, 13])]

In [ ]:
## create ranks here
## i.e. [1,2,3]
## schedule with [1] will have score 3
## schedule with [2] will have score 2
## schedule with [3] will have score 1
## utility is sum of scores, sort bundles by highest utility


def generate_demand_set(arr, max_bundle_size):
    possible_bundles = []
    for i in range(len(arr)):
        for j in range(i + 1, len(arr) + 1):
            bundle = arr[i:j]
            possible_bundles.append((sum(bundle), bundle))
    #put in order of utility
    possible_bundles.sort(key=lambda x: (x[0], len(x[1])), reverse=True)
    #get rid of bundles that are too large
    final_possible_bundles = [x[1] for x in possible_bundles if len(x) <= max_bundle_size]
    return final_possible_bundles



In [ ]:
rank=sample_course_ranking("GSUNDC3")

all_demand_sets = []
for student in rank:
  demand_set = generate_demand_set(student, 3)
  all_demand_sets.append(demand_set)

all_demand_sets



[[array([16, 13]), array([16]), array([13])],
 [array([15, 14, 28]),
  array([14, 28]),
  array([15, 14]),
  array([28]),
  array([15]),
  array([14])],
 [array([16, 13]), array([16]), array([13])],
 [array([13,  9]), array([13]), array([9])],
 [array([19])],
 [array([14, 15]), array([15]), array([14])],
 [array([9])],
 [array([13])],
 [array([14, 16]), array([16]), array([14])],
 [array([42])],
 [array([19, 16]), array([19]), array([16])],
 [array([15, 13]), array([15]), array([13])],
 [array([9])],
 [array([13, 14]), array([14]), array([13])],
 [],
 [array([13, 15]), array([15]), array([13])],
 [array([15, 37, 13]),
  array([15, 37]),
  array([37, 13]),
  array([37]),
  array([15]),
  array([13])],
 [],
 [array([13])],
 [array([15, 16, 35]),
  array([16, 35]),
  array([35]),
  array([15, 16]),
  array([16]),
  array([15])],
 [array([22, 16, 17,  9]),
  array([22, 16, 17]),
  array([16, 17,  9]),
  array([22, 16]),
  array([16, 17]),
  array([17,  9]),
  array([22]),
  array([17]),
  