In [1]:
import pandas as pd
import numpy as np

In [2]:
# waitlist and enrollment data
wl=pd.read_csv("onlywaitlists.csv")
wl

Class        Data  BCCR1  BCCR2  BCCR3  BCCR4  CCCOMA3  CCCOMA4  \
0      TOTALS         NaN    132    131    106     89        9       10   
1   CBMFW4761  enrollment      1      1      1      2        0        0   
2   CBMFW4761    waitlist      0      0      0      0        0        0   
3   COMSE6111  enrollment      0      0      0      0        0        0   
4   COMSE6111    waitlist      0      0      0      3        0        0   
..        ...         ...    ...    ...    ...    ...      ...      ...   
82  CSEEW4840    waitlist      0      0      0      0        0        0   
83  CSORW4231  enrollment      0      0      0      0        0        0   
84  CSORW4231    waitlist      0      0      7      3        2        0   
85  ENGIE1006  enrollment      7      9      1      2        0        0   
86  ENGIE1006    waitlist      0      0      0      0        0        0   

    CCCOMS3  CCCOMS4  ...  GOSTAT2  GSCSCA3  GSCSCA4  GSFNEC4  GSUNDC2  \
0       103      108  ...        0       62      109        5       35   
1         3        0  ...        0        0        4        0        0   
2         0        0  ...        0        0        0        0        0   
3         0        0  ...        0        0        0        0        0   
4         5       12  ...        0        2        5        0        0   
..      ...      ...  ...      ...      ...      ...      ...      ...   
82        0        1  ...        0        1        1        0        0   
83        0        0  ...        0        0        0        0        0   
84        5        4  ...        0        6        7        0        0   
85        0        1  ...        0        0        0        1        3   
86        0        0  ...        0        0        0        0        0   

    GSUNDC3  PHBION1  OTHER  Total    Cap  
0        42        0    NaN    NaN    NaN  
1         0        0   14.0   48.0   50.0  
2         0        0    0.0    0.0    NaN  
3         0        0    0.0    1.0   75.0  
4         0        0    5.0  172.0    NaN  
..      ...      ...    ...    ...    ...  
82        0        0    0.0   46.0    NaN  
83        0        0    0.0    0.0  200.0  
84        0        0   23.0  193.0    NaN  
85        2        0   22.0  184.0  200.0  
86        0        0    0.0    0.0    NaN  

[87 rows x 47 columns]

In [3]:
# data on what each of the group names mean
st=pd.read_csv( "students.csv")
st

Program                                       Program_Name  Degree  \
0   CCCOMA                   COMPUTER SCIENCE AND MATHEMATICS  AB       
1   CCCOMS                                   COMPUTER SCIENCE  AB       
2   CCCOST                    COMPUTER SCIENCE AND STATISTICS  AB       
3   CCDTSC  DATA SCIENCE                                  ...  AB       
4   CCINFS                               INFORMATION SCIENCES  AB       
5   CMCOMS                                   COMPUTER SCIENCE  AB       
6   CNCOMS                                   COMPUTER SCIENCE  AB       
7   CS/MBA         DUAL MS/MBA: COMPUTER SCIENCE AND BUSINESS  MS       
8   EACSIS                                Information Systems  CPF      
9   EACSIT                                Intelligent Systems  CPF      
10  EACSNS                             Networking and Systems  CPF      
11  EDCOMS                                   COMPUTER SCIENCE  DES      
12  EKCBIO                              COMPUTATIONAL BIOLOGY  NDG      
13  EKCSEC                                  COMPUTER SECURITY  NDG      
14  EKFDCS                    FOUNDATIONS OF COMPUTER SCIENCE  NDG      
15  EKMLRN                                   MACHINE LEARNING  NDG      
16  EKNLPR                        NATURAL LANGUAGE PROCESSING  NDG      
17  EKNSYS                                    NETWORK SYSTEMS  NDG      
18  EKPERS                                       PERSONALIZED  NDG      
19  EKSSYS                                   SOFTWARE SYSTEMS  NDG      
20  EKTHES                                             THESIS  NDG      
21  EKVSGR                                  VISION & GRAPHICS  NDG      
22  EMCOMS                                   COMPUTER SCIENCE  MS       
23  EMCSAP                     COMPUTER SCIENCE ALIGN PROGRAM  NDG      
24  EMCSJN           DUAL MS -- COMPUTER SCIENCE & JOURNALISM  MS       
25  EMIDSE  DATA SCIENCE                                  ...  MS       
26  EMIDSO  DATA SCIENCE ONLINE                           ...  MS       
27  ENCMEN                               COMPUTER ENGINEERING  BS       
28  ENCOMS                                   COMPUTER SCIENCE  BS       
29  EPCSE                        COMPUTER SYSTEMS ENGINEERING  CSE      
30  ESCOMS                                   COMPUTER SCIENCE  NDG      
31  ETCOMS                   MS/PHD TRACK -- COMPUTER SCIENCE  MS       
32  EUCSE                        COMPUTER SYSTEMS ENGINEERING  CSE      
33  EVCOMS                                   COMPUTER SCIENCE  MS       
34  EWCOMS                   MS/PHD TRACK -- COMPUTER SCIENCE  MS       
35  EYCOMS                                   COMPUTER SCIENCE  DES      
36  GCCOMS                                   COMPUTER SCIENCE  BS       
37  GCCSCA                                   COMPUTER SCIENCE  BA       
38  GDCOMS                                   COMPUTER SCIENCE  PHD      
39  GICOMS                                   COMPUTER SCIENCE  BS       
40  GLCOMS                                   COMPUTER SCIENCE  PHM      
41  GSCOMA                   COMPUTER SCIENCE AND MATHEMATICS  BA       
42  GSCOMS                                   COMPUTER SCIENCE  BS       
43  GSCOST                    COMPUTER SCIENCE AND STATISTICS  BA       
44  GSCSCA                                   COMPUTER SCIENCE  BA       
45  GSDTSC  DATA SCIENCE                                  ...  BA       
46  GSINFA                               INFORMATION SCIENCES  BA       
47  GSINFS                               INFORMATION SCIENCES  BS       
48  VMCOMS                                   COMPUTER SCIENCE  MS       

       Cert_Type School Department Bill_Program_Flag Interdisciplinary_Flag  \
0   MAJOR          CC         COMS                 Y                      N   
1   MAJOR          CC         COMS                 Y                      N   
2   MAJOR          CC         COMS                 Y                      N   
3   MAJOR          CC         COMS  

In [4]:
# sum together enrollment and waitlist data
wl_data=wl.groupby(['Class']).sum().reset_index()
# dtop the row the totals waitlist number per class
wl_data=wl_data.drop(43)
# drop excess column/rows, transpose to get groups as rows
wl_tr=wl_data.drop(['Class'], axis=1).transpose()
wl_tr=wl_tr.drop(["OTHER", "Total", "Cap"], axis=0)
# compute the total number of waitlists per group
wl_tr["total waitlists"]=wl_tr.sum(axis=1)
# total number of students in each group
wl_tr["total students"]=wl.iloc[0]

# compute the ratio betweem waitlists and total students
# this ratio can be interpeted as the average number of waitlists joined by students in this group
wl_tr["ratio"]=wl_tr["total waitlists"]/wl_tr["total students"]
# divide the number of waitlists per each course by the total number of waitlists
# this can be interpreted as the probability that a student in this group would join the waitlist for this particular class
wl_final=wl_tr[range(0,43)].div(wl_tr["total waitlists"], axis=0)
# bring back the previous columns, fill in naN values with 0
wl_final['waitlist']=wl_tr["total waitlists"]
wl_final['students']=wl_tr["total students"]
wl_final['ratio']=wl_tr["ratio"]
wl_final=wl_final.fillna(0)
wl_final

/var/folders/w5/65l6d67x3qbdqdqfxm1cnkhw0000gn/T/ipykernel_37867/934707582.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  wl_data=wl.groupby(['Class']).sum().reset_index()


0         1         2         3         4         5         6  \
BCCR1    0.005682  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
BCCR2    0.004167  0.000000  0.000000  0.004167  0.000000  0.000000  0.000000   
BCCR3    0.004587  0.000000  0.004587  0.032110  0.000000  0.000000  0.000000   
BCCR4    0.012048  0.018072  0.012048  0.024096  0.000000  0.006024  0.000000   
CCCOMA3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
CCCOMA4  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
CCCOMS3  0.011070  0.018450  0.000000  0.003690  0.000000  0.003690  0.003690   
CCCOMS4  0.000000  0.054299  0.004525  0.022624  0.000000  0.004525  0.000000   
CCFNEC3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
CCNDGV1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
CCUNDC1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
CCUNDC2  0.000000  0.002326  0.000000  0.000000  0.000000  0.002326  0.000000   
EMBUSA2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
EMCMEN1  0.000000  0.070866  0.015748  0.047244  0.007874  0.188976  0.000000   
EMCMEN2  0.000000  0.000000  0.000000  0.000000  0.000000  0.500000  0.000000   
EMCOMS1  0.005767  0.110727  0.008074  0.029988  0.003460  0.003460  0.013841   
EMCOMS2  0.031250  0.031250  0.000000  0.000000  0.000000  0.000000  0.000000   
EMCSAP1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
EMELEN1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
EMELEN2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
EMIDSE1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
EMIDSE2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
EMOPRE2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ENAPMA4  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ENCMEN2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ENCMEN3  0.000000  0.000000  0.016949  0.000000  0.000000  0.016949  0.000000   
ENCMEN4  0.000000  0.031746  0.000000  0.000000  0.000000  0.015873  0.000000   
ENCOMS2  0.003929  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ENCOMS3  0.010776  0.023707  0.002155  0.010776  0.002155  0.002155  0.002155   
ENCOMS4  0.014320  0.050119  0.002387  0.014320  0.004773  0.002387  0.011933   
ENOPRE3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ENUNDC1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ETCOMS1  0.083333  0.000000  0.000000  0.000000  0.027778  0.000000  0.000000   
ETCOMS2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
GOMAFN2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
GOSTAT2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
GSCSCA3  0.000000  0.011905  0.000000  0.000000  0.011905  0.000000  0.000000   
GSCSCA4  0.013699  0.017123  0.010274  0.006849  0.000000  0.006849  0.006849   
GSFNEC4  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
GSUNDC2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
GSUNDC3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
PHBION1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

           7         8         9  ...        36        37        38   39  \
BCCR1    0.0  0.000000  0.357955  ...  0.000000  0.005682  0.000000  0.0   
BCCR2    0.0  0.000000  0.058333  ...  0.000000  0.100000  0.000000  0.0   
BCCR3    0.0  0.000000  0.059633  ...  0.000000  0.055046  0.022936  0.0   
BCCR4    0.0  0.018072  0.024096  ...  0.000000  0.006024  0.018072  0.0   
CCCOMA3  0.0  0.000000  0.000000  ...  0.000000  0.076923  0.000000  0.0   
CCCOMA4  0.0  0.000000  0.000000  ...  0.000000  0.263158  0.000000  0.0   


In [5]:
# samples a normal distribution
# need to figure out standard deviation--> could ask for this data? or just use a random number like 1
# sets any negative values to 0
def sample_class_num(mean, std, N):
    sample=np.round(np.random.normal(mean, std, N))
    sample[sample<0]=0
    return sample

# randomly chooses courses according to the distribution
def course_ranking(class_num, course_prob):
    return np.random.choice(43,class_num,p=course_prob, replace=False)

# for a certain group compute a sample of course rankings
def sample_course_ranking(group):
    cr=wl_final.loc[group]
    class_num=sample_class_num(cr.ratio, 1, int(cr.students)).astype(int)
    vec=cr[range(0,43)]
    rank=[course_ranking(x, vec) for x in class_num]
    return rank


In [6]:
sample_class_num(4,1,10)

array([5., 3., 6., 4., 5., 3., 3., 4., 5., 6.])

In [7]:
#SLIGHT BUG HERE, probabilities don't sum to 1
rank=sample_course_ranking("GSUNDC3")
rank

[array([29]),
 array([15]),
 array([ 9, 28]),
 array([], dtype=int64),
 array([16, 13, 14]),
 array([13, 37, 15]),
 array([37]),
 array([13, 28]),
 array([13,  9]),
 array([14, 15]),
 array([], dtype=int64),
 array([ 9, 19]),
 array([28, 13]),
 array([15, 19]),
 array([13, 14, 33]),
 array([13,  9]),
 array([12, 14]),
 array([28, 14]),
 array([13]),
 array([22]),
 array([15, 12]),
 array([15, 37,  9]),
 array([], dtype=int64),
 array([37, 12, 15]),
 array([42, 15]),
 array([35, 15, 37]),
 array([], dtype=int64),
 array([13]),
 array([ 9, 14]),
 array([ 9, 16, 15]),
 array([28, 13, 17, 37]),
 array([9]),
 array([13, 15]),
 array([ 9, 37, 28]),
 array([17, 37, 13]),
 array([15, 13, 37]),
 array([15, 13]),
 array([42]),
 array([33, 13]),
 array([13, 14, 15]),
 array([15, 14]),
 array([15, 14])]

In [8]:
## create ranks here
## i.e. [1,2,3]
## schedule with [1] will have score 3
## schedule with [2] will have score 2
## schedule with [3] will have score 1
## utility is sum of scores, sort bundles by highest utility


def generate_demand_set(arr, max_bundle_size):
    possible_bundles = []
    for i in range(len(arr)):
        for j in range(i + 1, len(arr) + 1):
            bundle = arr[i:j]
            possible_bundles.append((sum(bundle), bundle))
    #put in order of utility
    possible_bundles.sort(key=lambda x: (x[0], len(x[1])), reverse=True)
    #get rid of bundles that are too large
    final_possible_bundles = [x[1] for x in possible_bundles if len(x) <= max_bundle_size]
    return final_possible_bundles



In [9]:
rank=sample_course_ranking("GSUNDC3")

all_demand_sets = []
for student in rank:
    demand_set = generate_demand_set(student, 3)
    all_demand_sets.append(demand_set)

all_demand_sets



[[array([14, 15,  9]),
  array([14, 15]),
  array([15,  9]),
  array([15]),
  array([14]),
  array([9])],
 [array([ 9, 42, 33]),
  array([42, 33]),
  array([ 9, 42]),
  array([42]),
  array([33]),
  array([9])],
 [array([15])],
 [array([28, 13]), array([28]), array([13])],
 [array([13])],
 [],
 [array([15,  9, 16]),
  array([ 9, 16]),
  array([15,  9]),
  array([16]),
  array([15]),
  array([9])],
 [array([14])],
 [array([28, 15]), array([28]), array([15])],
 [array([14, 13]), array([14]), array([13])],
 [array([13, 16]), array([16]), array([13])],
 [array([17, 13]), array([17]), array([13])],
 [array([15])],
 [array([28])],
 [array([15, 28]), array([28]), array([15])],
 [array([ 9, 16]), array([16]), array([9])],
 [array([15, 13, 28]),
  array([13, 28]),
  array([15, 13]),
  array([28]),
  array([15]),
  array([13])],
 [],
 [array([ 9, 17]), array([17]), array([9])],
 [array([ 9, 33, 13]),
  array([33, 13]),
  array([ 9, 33]),
  array([33]),
  array([13]),
  array([9])],
 [array([13])

In [10]:
rank=sample_course_ranking("GSUNDC3")
print(rank)
def get_all_demand_set(rank,max_bundle_size=3):
    all_demand_sets = []
    for student in rank:
        demand_set = generate_demand_set(student, max_bundle_size)
        all_demand_sets.append(demand_set)

    return all_demand_sets

[array([35,  9, 13, 37]), array([28, 13]), array([14,  9, 17]), array([], dtype=int64), array([15,  9, 16]), array([15]), array([22]), array([15, 13]), array([13]), array([15,  9, 12, 13]), array([15]), array([13]), array([15]), array([37, 13, 15, 14]), array([ 9, 14]), array([29]), array([28]), array([19, 37]), array([9]), array([13]), array([], dtype=int64), array([13, 15]), array([], dtype=int64), array([22, 13]), array([ 9, 14]), array([37]), array([35,  9]), array([42, 14]), array([37, 16, 13, 35]), array([15, 16]), array([14,  9]), array([37]), array([9]), array([], dtype=int64), array([12, 13]), array([13, 28, 15, 16, 19]), array([13]), array([9]), array([29, 15]), array([13, 19]), array([37]), array([15, 13])]


In [11]:
wl.fillna(0, inplace=True)
wl_data2=wl.groupby(['Class']).sum().reset_index()
wl_data2

/var/folders/w5/65l6d67x3qbdqdqfxm1cnkhw0000gn/T/ipykernel_37867/3397330978.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  wl_data2=wl.groupby(['Class']).sum().reset_index()


Class  BCCR1  BCCR2  BCCR3  BCCR4  CCCOMA3  CCCOMA4  CCCOMS3  CCCOMS4  \
0   CBMFW4761      1      1      1      2        0        0        3        0   
1   COMSE6111      0      0      0      3        0        0        5       12   
2   COMSE6156      0      0      1      2        0        0        0        1   
3   COMSE6178      0      1      7      4        0        0        1        5   
4   COMSE6261      0      0      0      0        0        0        0        0   
5   COMSE6424      0      0      0      1        0        0        1        1   
6   COMSE6732      0      0      0      0        0        0        1        0   
7   COMSE6915      0      0      0      0        0        0        0        0   
8   COMSE6998      0      0      0      3        0        0        7       11   
9   COMSW1004     63     14     13      4        0        0        0        0   
10  COMSW1404      3      0      0      0        0        0        0        0   
11  COMSW3102      0      0      4      0        0        0        3        1   
12  COMSW3132      0      3      6      1        0        0        2        0   
13  COMSW3134     60     26      5      2        0        0        0        0   
14  COMSW3157      9     26      6      6        2        1        3        1   
15  COMSW3203     31     57     15      5        0        0        4        1   
16  COMSW3261      0     27     26      8        3        1       38        7   
17  COMSW4111      0     21     22     12        1        1       19       11   
18  COMSW4115      0      1      2      1        0        0       10        6   
19  COMSW4118      0      0      3      3        0        0       11        6   
20  COMSW4160      0      0      1      4        0        0        1        6   
21  COMSW4167      1      2      1      4        0        0        5        6   
22  COMSW4170      0     15     32     33        0        3       34       37   
23  COMSW4172      0      0      2      2        0        0        3        2   
24  COMSW4182      0      3      0      2        0        0        2        0   
25  COMSW4223      0      0      4      1        0        0        2        7   
26  COMSW4232      0      0      0      1        1        0        1        2   
27  COMSW4460      0      0      1      1        0        0        6        8   
28  COMSW4701      0      2      8      2        0        2       10        5   
29  COMSW4705      0      3     17     11        2        1       22       15   
30  COMSW4721      0      0      2      2        0        0        0        0   
31  COMSW4732      0      1      1     11        0        1       13       21   
32  COMSW4733      0      0      2      2        0        0        6        3   
33  COMSW4771      0      1      6      6        0        0       10        5   
34  COMSW4773      0      0      0      0        0        0        0        0   
35  COMSW4995      0      3      5     18        1        4       21       23   
36  CSEEE6868      0      0      0      0        0        0        0        0   
37  CSEEW3827      1     24     12      1        1        5       14        4   
38  CSEEW4119      0      0      5      3        0        0        8        8   
39  CSEEW4121      0      0      0      0        0        0        0        0   
40  CSEEW4840      0      0      0      0        0        0        0        1   
41  CSORW4231      0      0      7      3        2        0        5        4   
42  ENGIE1006      7      9      1      2        0        0        0        1   
43     TOTALS    132    131    106     89        9       10      103      108   

    CCFNEC3  ...  GOSTAT2  GSCSCA3  GSCSCA4  GSFNEC4  GSUNDC2  GSUNDC3  \
0         0  ...        0        0        4        0        0        0   
1         0  ...        0        2        5        0        0        0   
2         0  ...        0        0        3        0        0        0   
3         0  ...        0        0        2        0        0     

In [12]:
# Creates a dataframe of 1's and 0's for the specified group
# based on the demand set that provides the highest 
# utility (i.e. the first set  returned from get_all_demand_set(rank, bundle_size) 
def allocate_group(group_demand_sets):
    max_demand_set=[]
    for i,demand in enumerate(group_demand_sets):
        if len(demand) != 0:
            max_demand_set.append(demand[0])
            
    rows = len(wl_data2)
    columns = len(max_demand_set)
    matrix_of_zeros = np.zeros((rows, columns))

    df_allocation=pd.DataFrame(matrix_of_zeros)
    df_allocation['Class']=wl_data2['Class']
    last_column = df_allocation.columns[-1]

    # Move the last column to the first position
    df_allocation = df_allocation[[last_column] + [col for col in df_allocation.columns if col != last_column]]

    for i,classes in enumerate(max_demand_set):
        j=0
        while j <len(classes):
            df_allocation.iloc[classes[j],i]=1
            j+=1
            
            
    return df_allocation

In [13]:
def one_hot_encode(input_list):
    encoded_vector = np.zeros(43)
    encoded_vector[input_list] = 1
    return encoded_vector.tolist()

def demand_set_to_one_hot(all_demand_set):
	one_hot_demand_sets = []
	for student_ds in all_demand_set: 
		student_one_hot_ds = []
		for bundle in student_ds: 
			one_hot = one_hot_encode(bundle)
			student_one_hot_ds.append(one_hot)
		one_hot_demand_sets.append(student_one_hot_ds)
	return one_hot_demand_sets

def one_hot_to_demand_set(all_one_hot_demand_sets):
	demand_sets = []
	for student_one_hot_ds in all_one_hot_demand_sets:
		student_demand_set = []
		for bundle in student_one_hot_ds: 
			student_demand_set.append([index for index, value in enumerate(bundle) if value == 1])
		demand_sets.append(student_demand_set)
	return demand_sets 


In [14]:
def get_prices_for_each_allocation(prices, student_demand_set):
	price_for_each_demand_set = []
	for demand_set in student_demand_set: 
		prices_np = np.array(prices)
		demand_set_np = np.array(demand_set).T
		total_price = prices_np.dot(demand_set_np)
		print(total_price)
		price_for_each_demand_set.append(total_price[0])
	
	return price_for_each_demand_set

def budget_perterbations(prices, student_demand_set): 
	# input: prices for each course & demand set for a student 
	# prices = [.3, .2, .1, .5] (ie, price of course at idx 0 is 0.3, price of course at idx 1 is 0.2)
	# student_demand_set = [[1,1,0,0], [1,0,0,0],[0,1,0,0]] where a student's most preferred bundle is [1,1,0,0] and they get classes 0 and 1
	# second preferred bundle is [1,0,0,0] where the student would get only class 0, etc. 

	# output: budget allocation for each student, ie if they spent 0.2 to 0.5 (noninclusive), they would want allocation [1,0,0,0]
	# if they spent 0.5 or more, they would want allocation [1,1,0,0]

	#idx 0 price is for the top ranked bundle 
	if len(student_demand_set) == 0:
		return ([],[])
	
	price_for_each_demand_set = get_prices_for_each_allocation(prices,student_demand_set)
	print(price_for_each_demand_set)
	allocations = []
	budget_intervals = []
	last_min_price = max(price_for_each_demand_set) + 1

	for i, bundle_price in enumerate(price_for_each_demand_set): 
		if bundle_price < last_min_price: 
			allocations.append(student_demand_set[i])
			budget_intervals.append((bundle_price, last_min_price))
			last_min_price = bundle_price
	print("alloc: ", allocations)
	print("budget intervals: ", budget_intervals)

	return (allocations, budget_intervals)



In [16]:
rank=sample_course_ranking("CCCOMS3")
all_demand_set=get_all_demand_set(rank,3)
one_hot_demand_set = demand_set_to_one_hot(all_demand_set)
prices = np.random.rand(1, 43)

all_budget_perterbations = []
all_budget_intervals = []
for student_demand_set in one_hot_demand_set: 
	allocations, budget_intervals = budget_perterbations(prices, student_demand_set)
	all_budget_perterbations.append(allocations)
	all_budget_intervals.append(budget_intervals)

allocations = one_hot_to_demand_set(all_budget_perterbations)
print("FINAL ALLOC: ", allocations, len(allocations))

print(len(all_budget_perterbations), len(all_budget_intervals))




#df_CCCOMS3=allocate_group(GSCSCA3_demand_set)


[1.93137608]
[1.46159467]
[1.16845757]
[0.76291851]
[0.69867616]
[0.46978141]
[1.9313760807474212, 1.461594668676609, 1.16845757339001, 0.7629185073574113, 0.6986761613191979, 0.46978141207081214]
alloc:  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.